website/urls.py
from django.urls import path
from website.views import *


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("contact/", ContactView.as_view(), name="contact"),
    
    path("jobs/", JobsView.as_view(), name="jobs"),
    path("job_single/<int:id>/", JobDetailView.as_view(), name="job_single"),
    path("delete_job/<int:pk>/", JobDeleteView.as_view(), name="delete_job"),
    path("edit_job/<int:pk>/", JobEditView.as_view(), name="edit_job"),
    path("add_job/", JobCreateView.as_view(), name="add_job"),
    
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
]

website/models.py
from django.urls import reverse
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Vacancy(models.Model):
    company = models.CharField(max_length=255)
    position_title = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    employment_type = models.CharField(
        max_length=50,
        choices=[
            ("full_time", "Full Time"),
            ("part_time", "Part Time"),
            ("contract", "Contract"),
            ("internship", "Internship"),
            ("temporary", "Temporary"),
            ("remote", "Remote"),
            ("other", "Other"),
        ],
        default="full_time",
    )
    salary_from = models.PositiveIntegerField(null=True, blank=True)
    salary_to = models.PositiveIntegerField(null=True, blank=True)
    salary_note = models.CharField(max_length=100, default="Not stated")

    url = models.URLField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    active_until = models.DateField()

    job_description = models.TextField(help_text="Дозволено HTML для форматування")

    experience_required = models.CharField(
        max_length=100, blank=True, help_text="Наприклад, '2+ роки', 'Без досвіду'"
    )
    education_level = models.CharField(
        max_length=50,
        choices=[
            ("none", "No formal education"),
            ("high_school", "High School"),
            ("associate", "Associate Degree"),
            ("bachelor", "Bachelor's Degree"),
            ("master", "Master's Degree"),
            ("doctorate", "Doctorate/PhD"),
            ("other", "Other"),
        ],
        default="none",
        blank=True,
        help_text="Мінімальний необхідний рівень освіти",
    )
    industry = models.CharField(
        max_length=100,
        blank=True,
        help_text="Індустрія або сфера, наприклад, 'IT', 'Фінанси'",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    icon_id = models.PositiveSmallIntegerField(
        default=1,
        validators=[MinValueValidator(1), MaxValueValidator(10)],
        help_text="Випадковий id іконки від 1 до 10",
    )

    def get_absolute_url(self):
        return reverse("job_single", kwargs={"id": self.pk})

    class Meta:
        ordering = ["-publish_date"]

    def __str__(self):
        return f"{self.position_title} at {self.company}"

website/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import Vacancy


class SignupForm(forms.ModelForm):
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Пароль"}
        )
    )
    password2 = forms.CharField(
        label="Підтвердіть пароль",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Підтвердіть пароль"}
        ),
    )

    class Meta:
        model = User
        fields = ("username", "email")
        labels = {
            "username": "Ім'я користувача",
            "email": "Електронна адреса",
        }
        widgets = {
            "username": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Ім'я користувача"}
            ),
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Електронна адреса"}
            ),
        }

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError("Паролі не співпадають")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        "invalid_login": "Ви ввели невірне ім'я користувача або пароль. Будь ласка, перевірте ще раз і спробуйте знову.",
        "inactive": "Цей обліковий запис неактивний. Будь ласка, зверніться до служби підтримки."
    }


class JobForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = "__all__"
        labels = {
            "company": "Компанія",
            "position_title": "Назва вакансії",
            "location": "Місцезнаходження",
            "employment_type": "Тип зайнятості",
            "salary_from": "Мінімальна зарплата",
            "salary_to": "Максимальна зарплата",
            "salary_note": "Примітка до зарплати",
            "url": "Посилання",
            "is_active": "Активна",
            "publish_date": "Дата публікації",
            "active_until": "Актуально до",
            "job_description": "Опис вакансії",
            "experience_required": "Необхідний досвід",
            "education_level": "Освітній рівень",
            "industry": "Індустрія",
            "icon_id": "Іконка",
        }
        widgets = {
            "position_title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Введіть назву вакансії"}
            ),
            "job_description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 5,
                    "placeholder": "Введіть опис вакансії",
                }
            ),
            "location": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Введіть місцезнаходження"}
            ),
            "salary_from": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Мінімальна зарплата"}
            ),
            "salary_to": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Максимальна зарплата"}
            ),
            "is_active": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name not in ["is_active", "employment_type"]:
                field.widget.attrs["class"] = (
                    field.widget.attrs.get("class", "") + " form-control"
                )

website/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.views import LoginView, LogoutView
from .forms import CustomAuthenticationForm, JobForm, SignupForm

from django.contrib import messages
from django.contrib.auth import login as auth_login

from .models import Vacancy
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.views.generic.edit import FormView
from django.contrib.auth import login as auth_login
from django.contrib import messages


class HomeView(TemplateView):
    template_name = "website/pages/home.html"


class ContactView(TemplateView):
    template_name = "website/pages/contact.html"


class CustomLoginView(LoginView):
    template_name = "website/account/login.html"
    authentication_form = CustomAuthenticationForm
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("home")


class SignupView(FormView):
    template_name = "website/account/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        messages.success(self.request, "Signup successful. You are now logged in.")
        return super().form_valid(form)


class CustomLogoutView(LogoutView):
    template_name = "website/account/logout.html"
    next_page = reverse_lazy("home")


class JobDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Vacancy
    template_name = "website/pages/job_confirm_delete.html"
    success_url = reverse_lazy("jobs")

    def test_func(self):
        return self.request.user.is_staff


class JobsView(ListView):
    model = Vacancy
    template_name = "website/pages/jobs.html"
    context_object_name = "vacancies"

    def get_queryset(self):
        return Vacancy.objects.filter(is_active=True).order_by("-publish_date")


class JobDetailView(DetailView):
    model = Vacancy
    template_name = "website/pages/job_single.html"
    context_object_name = "vacancy"
    pk_url_kwarg = "id"

    def get_object(self, queryset=None):
        return super().get_object(queryset)


class JobCreateView(LoginRequiredMixin, CreateView):
    model = Vacancy
    form_class = JobForm
    template_name = "website/pages/job_add.html"

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())


class JobEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Vacancy
    form_class = JobForm
    template_name = "website/pages/job_edit.html"
    context_object_name = "form"
    pk_url_kwarg = "pk"

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse_lazy("job_single", kwargs={"id": self.get_object().pk})

website/templates/website/pages/contact.html
{% extends 'website/parts/base.html' %}
{% load static %}
{% block title %}
  Контакти
{% endblock %}
{% block content %}
  <div class="bradcam_area bradcam_bg_1">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="bradcam_text">
            <h3>Контакти</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <section class="contact-section section_padding">
    <div class="container">
      <div class="d-none d-sm-block mb-5 pb-4">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3220435.953095259!2d-82.06624211743056!3d37.97813314448245!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x884cd670bdbcb2cd%3A0xc04e4149b746a695!2sVirginia%2C%20USA!5e0!3m2!1sen!2sua!4v1765299579758!5m2!1sen!2sua" width="100%" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>

      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Зв"яжіться з нами</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" placeholder="Введіть повідомлення"></textarea>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Введіть ваше ім'я'" placeholder="Введіть ваше ім'я" />
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Введіть електронну адресу'" placeholder="Введіть електронну адресу" />
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Тема'" placeholder="Тема" />
                </div>
              </div>
            </div>
            <div class="form-group mt-3">
              <button type="submit" class="button button-contactForm btn_4 boxed-btn">Надіслати</button>
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Buttonwood, California.</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>00 (440) 9865 562</h3>
              <p>Пн–Пт 9:00–18:00</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>support@colorlib.com</h3>
              <p>Надсилайте запит у будь-який час!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

website/templates/website/pages/home.html
{% extends 'website/parts/base.html' %}
{% load static %}
{% block title %}
  Дошка вакансій
{% endblock %}
{% block content %}
  <div class="slider_area">
    <div class="single_slider d-flex align-items-center slider_bg_1">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-7 col-md-6">
            <div class="slider_text">
              <h5 class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".2s">4537+ вакансій</h5>
              <h3 class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".3s">Знайдіть роботу мрії</h3>
              <p class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".4s">Ми допомагаємо знайти роботу швидко та просто</p>
              <div class="sldier_btn wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".5s">
                <a href="{% url 'jobs' %}" class="boxed-btn3">Знайти роботу</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="ilstration_img wow fadeInRight d-none d-lg-block text-right" data-wow-duration="1s" data-wow-delay=".2s">
      <img src="{% static 'img/banner/illustration.png' %}" alt="" />
    </div>
  </div>
{% endblock %}

website/templates/website/pages/job_add.html
{% extends 'website/parts/base.html' %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/pages/job-edit.css' %}" />
{% endblock %}

{% block title %}
  Додати вакансію
{% endblock %}
{% block content %}
  <main class="job-edit">
    <div class="container mt-5">
      <h1 class="text-center text-white">Додати вакансію</h1>
      <form method="POST" class="mt-4">
        <section class="row justify-content-center">
          <div class="col-6 form-group p-4 bg-white rounded">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Додати вакансію</button>
          </div>
        </section>
      </form>
    </div>
  </main>
{% endblock %}

website/templates/website/pages/job_edit.html
{% extends 'website/parts/base.html' %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/pages/job-edit.css' %}" />
{% endblock %}

{% block title %}
  Редагувати вакансію
{% endblock %}
{% block content %}
  <main class="job-edit">
    <div class="container mt-5">
      <h1 class="text-center text-white">Редагувати вакансію</h1>
      <form method="POST" class="mt-4">
        <section class="row justify-content-center">
          <div class="col-6 form-group p-4 bg-white rounded">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Зберегти</button>
          </div>
        </section>
      </form>
    </div>
  </main>
{% endblock %}

website/templates/website/pages/job_single.html
{% extends 'website/parts/base.html' %}
{% load static %}
{% block title %}
  Деталі вакансії
{% endblock %}
{% block content %}
  <div class="bradcam_area bradcam_bg_1">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="bradcam_text">
            <h3>{{ vacancy.position_title }}</h3>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="job_details_area">
    <section class="row mb-4">
      <div class="col">
        <div class="container">
          <a href="{% url 'jobs' %}" class="btn btn-secondary btn-sm mb-2">&larr; До всіх вакансій</a>
        </div>
      </div>
    </section>
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="job_details_header">
            <div class="single_jobs white-bg d-flex justify-content-between">
              <div class="jobs_left d-flex align-items-center">
                <div class="thumb">
                  {% if vacancy %}
                    <img src="{% static 'img/svg_icon/' %}{{ vacancy.icon_id }}.svg" alt="icon" />
                  {% endif %}
                </div>
                <div class="jobs_conetent">
                  <a href="#"><h4>{{ vacancy.position_title }}</h4></a>
                  <div class="links_locat d-flex align-items-center">
                    <div class="location">
                      <p>
                        <i class="fa fa-map-marker"></i> {{ vacancy.location }}
                      </p>
                    </div>
                    <div class="location">
                      <p>
                        <i class="fa fa-clock-o"></i> {{ vacancy.get_employment_type_display }}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="jobs_right">
                <div class="apply_now"></div>
              </div>
            </div>
          </div>
          <div class="descript_wrap white-bg">
            <div class="single_wrap">
              <h4>Опис вакансії</h4>
              {% if vacancy %}
                <div>{{ vacancy.job_description|safe }}</div>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="job_sumary">
            <div class="summery_header">
              <h3>Коротко про вакансію</h3>
            </div>
            <div class="job_content">
              <ul>
                <li>
                  Опубліковано: <span>{{ vacancy.publish_date|date:'d M, Y' }}</span>
                </li>
                <li>
                  Активна до: <span>{{ vacancy.active_until|date:'d M, Y' }}</span>
                </li>
                <li>
                  Зарплата: <span>
                    {% if vacancy.salary_from or vacancy.salary_to %}
                      USD{% if vacancy.salary_from %}{{ vacancy.salary_from }}{% endif %}
                      {% if vacancy.salary_from and vacancy.salary_to %} - {% endif %}
                      {% if vacancy.salary_to %}{{ vacancy.salary_to }}{% endif %}
                    {% else %}
                      {{ vacancy.salary_note }}
                    {% endif %}
                  </span>
                </li>
                <li>
                  Місто: <span>{{ vacancy.location }}</span>
                </li>
                <li>
                  Тип зайнятості: <span>{{ vacancy.get_employment_type_display }}</span>
                </li>
                <li>
                  Компанія: <span>{{ vacancy.company }}</span>
                </li>
                <li>
                  Галузь: <span>{{ vacancy.industry }}</span>
                </li>
                <li>
                  Досвід: <span>{{ vacancy.experience_required }}</span>
                </li>
                <li>
                  Освітній рівень: <span>{{ vacancy.get_education_level_display }}</span>
                </li>
              </ul>
            </div>
          </div>
          <div class="share_wrap d-flex">
            <span>Подiлитись:</span>
            <ul>
              <li>
                <a href="#"><i class="fa fa-facebook"></i></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-google-plus"></i></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-twitter"></i></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-envelope"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/pages/jobs.html
{% extends 'website/parts/base.html' %}
{% load static %}
{% block title %}
  Вакансії
{% endblock %}

{% block content %}
  <div class="bradcam_area bradcam_bg_1">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="bradcam_text">
            <h3>Шукайте вакансії разом з нами!</h3>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="job_listing_area plus_padding">
    <div class="container">
      <div class="row">
        {% if user.is_authenticated %}
          <div class="container mb-4">
            <div class="row">
              <div class="col text-right">
                <a href="{% url 'add_job' %}" class="btn btn-success green-bg"><i class="fa fa-plus"></i> Додати вакансію</a>
              </div>
            </div>
          </div>
        {% endif %}
        <div class="job_lists m-0 w-100">
          <div class="row">
            {% for vacancy in vacancies %}
              <div class="col-lg-12 col-md-12">
                <div class="single_jobs white-bg d-flex justify-content-between">
                  <div class="jobs_left d-flex align-items-center">
                    {% if user.is_authenticated and user.is_staff %}
                      <div class="mr-3">
                        <a href="{% url 'edit_job' pk=vacancy.id %}" class="btn btn-outline-info"><i class="fa fa-edit"></i> Редагувати</a>
                      </div>
                      <div class="mr-3">
                        <form method="POST" action="{% url 'delete_job' pk=vacancy.id %}">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger"><i class="fa fa-trash fa-remove fa-trash-alt"></i></button>
                        </form>
                      </div>
                    {% endif %}
                    <div class="thumb">
                      <img src="{% static 'img/svg_icon/' %}{{ vacancy.icon_id }}.svg" alt="icon" />
                    </div>
                    <div class="jobs_conetent">
                      <a href="{% url 'job_single' id=vacancy.id %}"><h4>{{ vacancy.position_title }}</h4></a>
                      <div class="links_locat d-flex align-items-center">
                        <div class="location">
                          <p>
                            <i class="fa fa-map-marker"></i> {{ vacancy.location }}
                          </p>
                        </div>
                        <div class="location">
                          <p>
                            <i class="fa fa-clock-o"></i> {{ vacancy.get_employment_type_display }}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="jobs_right">
                    <div class="apply_now">
                      <a href="{% url 'job_single' id=vacancy.id %}" class="boxed-btn3">Вiдгукнутись</a>
                    </div>
                    <div class="date">
                      <p>Опубліковано: {{ vacancy.publish_date|date:'d M Y' }}</p>
                    </div>
                  </div>
                </div>
              </div>
            {% empty %}
              <div class="col-lg-12">
                <p>Вакансій не знайдено.</p>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}